FROM golang:1.20-alpine as build

WORKDIR /opt/app

# cache dependencies
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# build the playground binary
COPY *.go ./
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o ./bin/playground ./playground/main.go

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /opt/app/bin/playground /bin/playground

EXPOSE 8080

USER nonroot:nonroot

CMD [ "/bin/playground" ]
